
#dictionary that maps every note on the fretboard to a corresponding audio file name
audio_dictionary = {
    "A0": "audio\A0.wav",
    "A1": "audio\A1.wav",
    "A2": "audio\A2.wav",
    "A3": "audio\A3.wav",
    "A#0": "audio\A#0.wav",
    "A#1": "audio\A#1.wav",
    "A#2": "audio\A#2.wav",
    "A#3": "audio\A#3.wav",
    "B0": "audio\B0.wav",
    "B1": "audio\B1.wav",
    "B2": "audio\B2.wav",
    "B3": "audio\B3.wav",
    "C0": "audio\C0.wav",
    "C1": "audio\C1.wav",
    "C2": "audio\C2.wav",
    "C3": "audio\C3.wav",
    "C#0": "audio\C#0.wav",
    "C#1": "audio\C#1.wav",
    "C#2": "audio\C#2.wav",
    "C#3": "audio\C#3.wav",
    "D0": "audio\D0.wav",
    "D1": "audio\D1.wav",
    "D2": "audio\D2.wav",
    "D3": "audio\D3.wav",
    "D#0": "audio\D#0.wav",
    "D#1": "audio\D#1.wav",
    "D#2": "audio\D#2.wav",
    "E0": "audio\E0.wav",
    "E1": "audio\E1.wav",
    "E2": "audio\E2.wav",
    "E3": "audio\E3.wav",
    "F0": "audio\F0.wav",
    "F1": "audio\F1.wav",
    "F2": "audio\F2.wav",
    "F3": "audio\F3.wav",
    "F0": "audio\F0.wav",
    "F1": "audio\F1.wav",
    "F2": "audio\F2.wav",
    "F3": "audio\F3.wav",
}

min_pent_audio_positions = {
    "A1": ["G0","A0","C0","D0","E1","G1","A1","C1","D1","E2","G2","A2"],
    "A2": ["A0","C0","D0","E1","G1","A1","C1","D1","E2","G2","A2","C2"],
    "A3": ["C0","D0","E1","G1","A1","C1","D1","E2","G2","A2","C2","D2"],
    "A4": ["D0","E1","G1","A1","C1","D1","E2","G2","A2","C2","D2","E3"],
    "A5": ["E1","G1","A1","C1","D1","E2","G2","A2","C2","D2","E3","G3"],
}
